package com.multissue.wit.feature.chat.dummy

import com.multissue.wit.feature.chat.state.ChatRoomInfoState

val chatRoomsDummy = listOf(
    ChatRoomInfoState(
        id = 1,
        emoji = "🏞️",
        title = "제주도 성산일출봉 같이 가요",
        lastMessage = "내일 오전 9시에 출발할게요!",
        lastMessageTime = "오전 9:41",
        unreadCount = 3,
        participantCount = 2,
        currentCount = 2,
        maxCount = 4,
        location = "제주 서귀포시",
        meetingDate = "오늘",
        dateTime = "3월 10일",
    ),
    ChatRoomInfoState(
        id = 2,
        emoji = "🏖️",
        title = "부산 해운대 당일치기",
        lastMessage = "좋아요~ 같이 가요",
        lastMessageTime = "어제",
        unreadCount = 0,
        participantCount = 1,
        currentCount = 1,
        maxCount = 2,
        location = "부산 해운대구",
        meetingDate = "내일",
        dateTime = "3월 12일",
    ),
    ChatRoomInfoState(
        id = 3,
        emoji = "🏺",
        title = "경주 역사 투어 동행 구합니다",
        lastMessage = "사진 찍을 때 렌즈 좀 빌려도 될까요?",
        lastMessageTime = "월요일",
        unreadCount = 1,
        participantCount = 3,
        currentCount = 3,
        maxCount = 4,
        location = "경북 경주시",
        meetingDate = "3월 15일",
        dateTime = "3월 15일",
    ),
    ChatRoomInfoState(
        id = 4,
        emoji = "☕",
        title = "강릉 커피거리 + 정동진",
        lastMessage = "네 알겠습니다 :)",
        lastMessageTime = "3/1",
        unreadCount = 100,
        participantCount = 2,
        currentCount = 2,
        maxCount = 3,
        location = "강원 강릉시",
        meetingDate = "3월 20일",
        dateTime = "3월 20일",
    ),
)
